const NavigationRoutes = {
    AUTH_STACK: {
      LOGIN: 'LOGIN_SCREEN',
      SIGN_UP: 'SIGNUP_SCREEN',
      AUTH_PHONENUMBER: 'AUTH_PHONENUMBER',
      OTP: 'OTP',
      SPLASH_SCREEN: 'SPLASH_SCREEN',
      AUTH_NAME: 'AUTH_NAME_SCREEN',
      AUTH_CITY: ' AUTH_CITY_SCREEN',
      PRIVACY_POLICY: 'PRIVACY_POLICY',
    },
    APP_STACK: {
      HOME: 'HOME_SCREEN',
      RIDES: 'RIDES',
      CHAT_SCREEN: 'CHAT_SCREEN',
      DRIVER_CHAT: 'DRIVER_CHAT',
      CORPORTATE_SETTINGS: 'CORPORTATE_SETTINGS',
      TRIP_DETAILS: 'TRIP_DETAILS',
      PROFILE: 'PROFILE',
      CITY_SELECTION: 'CITY_SELECTION',
      BOOKING_SCREEN: 'BOOKING_SCREEN',
      ADD_FUND: 'ADD_FUND_SCREEN',
      NOTIFICATION: 'NOTIFICATION',
      TIP_DRIVER: 'TIP_DRIVER',
      EARNINGS: 'EARNINGS',
      STRIPE_CONNECT: 'STRIPE_CONNECT',
      STRIPE_CONNECT_ID: 'STRIPE_CONNECT_ID',
      BANKING_INFO: 'BANKING_INFO',
      SERVICE_TYPES: "SERVICE_TYPES",
      DOCUMENTS: "DOCUMENTS"
    },
  };
  
  export default NavigationRoutes;
  